# docker-compose.yml
# ----------------------------------------------------------------------------
# Composes Docker containers and volumes to a runnable application
# ----------------------------------------------------------------------------
#
---
services:

  backend:
    image: docker.cloudtrain.aws.msgoat.eu/cloudtrain/cnj-security-oidc-backend-quarkus:latest
    ports:
      - "38080:8080"
    environment:
      DOCKER_JAVA_OPTS: "-Xms1G -Xmx1G"
      MP_JWT_VERIFY_PUBLICKEY_LOCATION: "https://oidc.cloudtrain.aws.msgoat.eu/realms/cloudtrain/protocol/openid-connect/certs"
      MP_JWT_VERIFY_ISSUER: "https://oidc.cloudtrain.aws.msgoat.eu/realms/cloudtrain"
